import pandas as pd
in_csv = "log_3.csv"
number_lines = sum(1 for row in (open(in_csv)))
block_rows = 10000
n = 1
col_names = ['Domain',
             'Receive Time',
             'Serial #',
             'Type',
             'Threat/Content Type',
             'Config Version',
             'Generate Time',
             'Source address',
             'Destination address',
             'NAT Source IP',
             'NAT Destination IP',
             'Rule',
             'Source User',
             'Destination User',
             'Application',
             'Virtual System',
             'Source Zone',
             'Destination Zone',
             'Inbound Interface',
             'Outbound Interface',
             'Log Action',
             'Time Logged',
             'Session ID',
             'Repeat Count',
             'Source Port',
             'Destination Port',
             'NAT Source Port',
             'NAT Destination Port',
             'Flags',
             'IP Protocol',
             'Action',
             'Bytes',
             'Bytes Sent',
             'Bytes Received',
             'Packets',
             'Start Time',
             'Elapsed Time (sec)',
             'Category',
             'tpadding',
             'Sequence Number',
             'Action Flags',
             'Source Country',
             'Destination Country',
             'cpadding',
             'Packets Sent',
             'Packets Received',
             'Session End Reason',
             'DG Hierarchy Level 1',
             'DG Hierarchy Level 2',
             'DG Hierarchy Level 3',
             'DG Hierarchy Level 4',
             'Virtual System Name',
             'Device Name',
             'Action Source',
             'Source VM UUID',
             'Destination VM UUID',
             'Tunnel ID/IMSI',
             'Monitor Tag/IMEI',
             'Parent Session ID',
             'Parent Session Start Time',
             'Tunnel',
             'SCTP Association ID',
             'SCTP Chunks',
             'SCTP Chunks Sent',
             'SCTP Chunks Received',
             'UUID for rule',
             'HTTP/2 Connection',
             'link_change_count',
             'policy_id',
             'link_switches',
             'sdwan_cluster',
             'sdwan_device_type',
             'sdwan_cluster_type',
             'sdwan_site',
             'dynusergroup_name']

for i in range(1,number_lines,block_rows):
    df = pd.read_csv(in_csv,
            low_memory=False,
            header=0,
            nrows = block_rows,
            skiprows = i)
    out_csv = 'log_3_' + str(n) + '.csv'
    df.to_csv(out_csv,
            index=False,
            header=col_names,
            mode='a',
            chunksize=block_rows)
    n = n+1
